apiVersion: v1
kind: Pod
metadata:
  name: cloudflared
spec:
  containers:
  - name: cloudflared
    image: cloudflare/cloudflared:2024.10.0
    command: ["cloudflared", "tunnel", "--no-autoupdate", "run"]
    env:
      - name: TUNNEL_TOKEN
        valueFrom:
          secretKeyRef:
            name: secret
            key: token
