name: Terraform plan

on:
  pull_request:
    paths:
      - 'terraform/**'

  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Create tfvars file
        run: echo "cloudflare_api_token = \"${{ secrets.CLOUDFLARE_API_TOKEN }}\"" > terraform.tfvars

      - name: Create tfbackend file
        run: |
          cat << EOF > config.s3.tfbackend
          access_key = "${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}"
          secret_key = "${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}"
          EOF

      - name: Initialize Terraform
        run: terraform init -backend-config=config.s3.tfbackend

      - name: Execute Terraform plan
        run: terraform plan -out=plan.tfplan

      - uses: reproio/terraform-j2md@92a5431c6a32baf8321bc57c9408f3972b161a77 # v0.0.9

      - name: Convert plan to Markdown
        run: terraform show -json plan.tfplan | terraform-j2md > plan.md

      - name: Comment on PR
        run: gh pr comment ${{ github.event.number }} --body-file plan.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
